# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- uat

pool:
  vmImage: ubuntu-latest

steps:
- script: echo testing...
  displayName: 'test unit'

- script: echo testing...
  displayName: 'scan sonar'

- task: Bash@3
  inputs:
    targetType: "inline"
    script: |
      curl -X POST -d {} "https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=2ebe044e-b6b7-49dd-9bcd-02cf18df035b&token=HRr0g5hn4iAAqkMebexJKqKZzOG79JI4nTUgOcehzUA&operation=startbuild" -H "Content-Type:application/json"
  displayName: 'deploy AWS Amplify'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS - Sangiraldome'
    regionName: 'us-east-1'
    scriptType: "inline"
    inlineScript: |
      while [ true ]
      do
      status=$(aws amplify list-jobs --app-id dilmzste6d5ct --branch uat | jq -r '.jobSummaries[0].status')
      echo "Amplify status: " $status
      echo "Deployment in progress..."
      if [[ $status == "SUCCEED" ]]; then
          echo "---Successful deployment---"
          break
      elif [[ "$status" == "FAILED" ]]; then
          echo "---Deploy failed---"
          exit 1
      fi
      sleep 20
      done
  displayName: Validate deployment Amplify
